services:
  postgress:
    image: postgres:16-alpine
    container_name: laporan-postgres
    environment:
      POSTGRES_USER: majapahit
      POSTGRES_PASSWORD: Madiun@123
      POSTGRES_DB: laporan-kertas-kerja
    ports:
      - "5432:5432"
    networks:
      - laporan-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: laporan-redis
    ports:
      - "6379:6379"
    networks:
      - laporan-network

networks:
  laporan-network:
    driver: bridge

volumes:
  db-data: