CREATE TABLE IF NOT EXISTS perjanjian_kinerja (
    id BIGSERIAL PRIMARY KEY,
    nama_pegawai VARCHAR (100) NOT NULL,
    id_rencana_kinerja VARCHAR(100) NOT NULL UNIQUE,
    nama_rencana_kinerja VARCHAR (255) NOT NULL,
    kode_program VARCHAR (100) NOT NULL,
    program VARCHAR (100) NOT NULL,
    kode_kegiatan VARCHAR (100) NOT NULL,
    kegiatan VARCHAR (100) NOT NULL,
    kode_sub_kegiatan VARCHAR (100) NOT NULL,
    sub_kegiatan VARCHAR (100) NOT NULL,
    pagu_anggaran INTEGER,
    indikator VARCHAR (255) NOT NULL,
    target VARCHAR (20) NOT NULL,
    satuan VARCHAR (20) NOT NULL,
    status_rencana_kinerja VARCHAR (50),
    nama_atasan VARCHAR (100) NOT NULL,
    id_rencana_kinerja_atasan VARCHAR(100) NOT NULL UNIQUE,
    nama_rencana_kinerja_atasan VARCHAR (255) NOT NULL,
    kode_program_atasan VARCHAR (100) NOT NULL,
    program_atasan VARCHAR (50) NOT NULL,
    kode_kegiatan_atasan VARCHAR (100) NOT NULL,
    kegiatan_atasan VARCHAR (100) NOT NULL,
    kode_sub_kegiatan_atasan VARCHAR (100) NOT NULL,
    sub_kegiatan_atasan VARCHAR (100) NOT NULL,
    pagu_anggaran_atasan INTEGER,
    indikator_atasan VARCHAR (255) NOT NULL,
    target_atasan VARCHAR (20) NOT NULL,
    satuan_atasan VARCHAR (20) NOT NULL,
    status_rencana_kinerja_atasan VARCHAR (50),
    status VARCHAR (50),
    verifikator JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
)